/**
 * Land Optimizer PDF Export
 * Generates a feasibility-quality PDF report with site plan image + metrics tables.
 * Client-side only — call from a 'use client' component with dynamic import.
 */

import type { OptimizationResult } from './layoutOptimizer';

const BRAND_GREEN = [57, 255, 20] as const;   // neon green
const DARK_BG     = [15, 15, 15] as const;
const PANEL_BG    = [26, 26, 26] as const;
const MUTED       = [120, 120, 120] as const;
const WHITE       = [255, 255, 255] as const;
const WARN_YELLOW = [255, 193, 7] as const;
const RED         = [220, 53, 69] as const;

interface PDFOptions {
  result: OptimizationResult;
  facilityType: string;
  sitePlanDataUrl: string;       // canvas.toDataURL() from generateSitePlanCanvas
  address?: string;
  constraints: { budget: number };
}

export async function generateFeasibilityPDF(opts: PDFOptions): Promise<void> {
  // Dynamic import — browser only
  const { jsPDF } = await import('jspdf');
  await import('jspdf-autotable');

  const { result, facilityType, sitePlanDataUrl, address, constraints } = opts;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const PW = doc.internal.pageSize.getWidth();   // 215.9mm
  const PH = doc.internal.pageSize.getHeight();  // 279.4mm
  const ML = 15, MR = 15, MT = 15;
  const CW = PW - ML - MR;

  const facilityLabel: Record<string, string> = {
    paintball: 'Paintball Facility', airsoft: 'Airsoft Arena',
    trampoline: 'Trampoline Park', gellyball: 'Gellyball Field',
    fec: 'Family Entertainment Center',
  };

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const label = facilityLabel[facilityType] ?? 'Recreation Facility';
  const overBudget = result.costEstimate.total > constraints.budget;

  // ── Helper: add footer to every page ─────────────────────────────────────
  const addFooter = () => {
    const pageNum = (doc as any).internal.getNumberOfPages();
    doc.setPage(pageNum);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      `Generated by Land Optimizer — Specialty Insurance SC  ·  specialtyinsurancesc.com  ·  Page ${pageNum}`,
      PW / 2, PH - 8, { align: 'center' }
    );
    // thin rule
    doc.setDrawColor(...MUTED);
    doc.setLineWidth(0.2);
    doc.line(ML, PH - 12, PW - MR, PH - 12);
  };

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // PAGE 1 — COVER HEADER + SITE PLAN IMAGE
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  // Dark header band
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, PW, 40, 'F');

  // Green accent stripe
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 38, PW, 2, 'F');

  // Title
  doc.setFontSize(22);
  doc.setTextColor(...BRAND_GREEN);
  doc.setFont('helvetica', 'bold');
  doc.text(label.toUpperCase(), ML, 18);

  // Subtitle
  doc.setFontSize(11);
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'normal');
  doc.text('FACILITY FEASIBILITY REPORT', ML, 26);

  // Date + address (right-aligned)
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(dateStr, PW - MR, 18, { align: 'right' });
  if (address) doc.text(address, PW - MR, 25, { align: 'right' });

  // Prepared by
  doc.text('Prepared by Specialty Insurance SC', PW - MR, 32, { align: 'right' });

  // ── Site plan image ───────────────────────────────────────────────────────
  // Canvas is 1600×950 — scale to fit page width
  const IMG_H = Math.round((950 / 1600) * CW);
  doc.addImage(sitePlanDataUrl, 'PNG', ML, 46, CW, IMG_H, '', 'FAST');

  // ── Quick-stats row below image ───────────────────────────────────────────
  const statY = 46 + IMG_H + 6;
  const stats = [
    { label: 'FIELDS', value: String(result.metrics.fieldCount) },
    { label: 'CAPACITY', value: `${result.metrics.maxCapacity} players` },
    { label: 'UTILIZED', value: `${result.metrics.utilizationPercent}%` },
    { label: 'PARKING', value: `${result.layout.parking.spaces} spaces` },
    { label: 'ACREAGE', value: `${(result.metrics.totalArea / 43560).toFixed(2)} ac` },
  ];
  const boxW = CW / stats.length;
  stats.forEach((s, i) => {
    const bx = ML + i * boxW;
    doc.setFillColor(...PANEL_BG);
    doc.roundedRect(bx + 1, statY, boxW - 2, 18, 2, 2, 'F');
    doc.setFontSize(16);
    doc.setTextColor(...BRAND_GREEN);
    doc.setFont('helvetica', 'bold');
    doc.text(s.value, bx + boxW / 2, statY + 10, { align: 'center' });
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(s.label, bx + boxW / 2, statY + 16, { align: 'center' });
  });

  // Budget status bar
  const budgetY = statY + 22;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  if (overBudget) {
    doc.setTextColor(...RED);
    doc.text(`⚠  ESTIMATED TOTAL $${result.costEstimate.total.toLocaleString()} — OVER BUDGET by $${(result.costEstimate.total - constraints.budget).toLocaleString()}`, ML, budgetY);
  } else {
    doc.setTextColor(40, 200, 80);
    doc.text(`✓  ESTIMATED TOTAL $${result.costEstimate.total.toLocaleString()} — WITHIN BUDGET ($${(constraints.budget - result.costEstimate.total).toLocaleString()} remaining)`, ML, budgetY);
  }

  addFooter();

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // PAGE 2 — DETAILED METRICS + COST BREAKDOWN
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  doc.addPage();

  // Page header
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, PW, 14, 'F');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND_GREEN);
  doc.setFont('helvetica', 'bold');
  doc.text('DETAILED METRICS  ·  ' + label.toUpperCase(), ML, 9);

  let curY = MT + 8;

  // ── Cost breakdown ────────────────────────────────────────────────────────
  sectionTitle(doc, 'COST BREAKDOWN', ML, curY); curY += 7;

  const costRows: [string, string][] = [
    ['Playing Fields', `$${result.costEstimate.fields.toLocaleString()}`],
    ['Support Facilities', `$${result.costEstimate.facilities.toLocaleString()}`],
    ['Parking', `$${result.costEstimate.parking.toLocaleString()}`],
  ];
  if (result.costEstimate.grading > 0) {
    costRows.push(['Site Grading (terrain)', `$${result.costEstimate.grading.toLocaleString()}`]);
  }
  costRows.push(['Permits & Fees', `$${result.costEstimate.permits.toLocaleString()}`]);

  (doc as any).autoTable({
    startY: curY,
    margin: { left: ML, right: MR },
    head: [['Line Item', 'Estimate']],
    body: costRows,
    foot: [[
      { content: 'TOTAL ESTIMATE', styles: { fontStyle: 'bold', fontSize: 11 } },
      {
        content: `$${result.costEstimate.total.toLocaleString()}`,
        styles: { fontStyle: 'bold', fontSize: 11, textColor: overBudget ? RED : [40, 200, 80] },
      },
    ]],
    headStyles: { fillColor: DARK_BG, textColor: BRAND_GREEN, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fillColor: [20, 20, 20], textColor: WHITE, fontSize: 10 },
    footStyles: { fillColor: PANEL_BG, textColor: WHITE },
    alternateRowStyles: { fillColor: PANEL_BG },
    columnStyles: { 1: { halign: 'right' } },
    theme: 'plain',
  });

  curY = (doc as any).lastAutoTable.finalY + 10;

  // Budget
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`Budget: $${constraints.budget.toLocaleString()}`, ML, curY);
  curY += 10;

  // ── Property metrics ──────────────────────────────────────────────────────
  sectionTitle(doc, 'PROPERTY METRICS', ML, curY); curY += 7;

  (doc as any).autoTable({
    startY: curY,
    margin: { left: ML, right: MR },
    body: [
      ['Total Area', `${result.metrics.totalArea.toLocaleString()} sq ft  (${(result.metrics.totalArea / 43560).toFixed(2)} acres)`],
      ['Usable Area', `${result.metrics.usableArea.toLocaleString()} sq ft`],
      ['Space Utilized', `${result.metrics.utilizationPercent}%`],
      ['Playing Fields', result.metrics.fieldCount.toString()],
      ['Max Player Capacity', result.metrics.maxCapacity.toString()],
      ['Parking Spaces', result.layout.parking.spaces.toString()],
      ...(result.layout.entryPoint
        ? [['Road Access', `${result.layout.entryPoint.side.toUpperCase()} entry${result.layout.entryPoint.roadName ? ' — ' + result.layout.entryPoint.roadName : ''}`]]
        : []),
    ],
    bodyStyles: { fillColor: [20, 20, 20], textColor: WHITE, fontSize: 10 },
    alternateRowStyles: { fillColor: PANEL_BG },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60, textColor: MUTED as any } },
    showHead: false,
    theme: 'plain',
  });

  curY = (doc as any).lastAutoTable.finalY + 10;

  // ── Field specifications ──────────────────────────────────────────────────
  if (curY > PH - 80) { doc.addPage(); addFooter(); curY = MT + 8; }

  sectionTitle(doc, 'FIELD SPECIFICATIONS', ML, curY); curY += 7;

  (doc as any).autoTable({
    startY: curY,
    margin: { left: ML, right: MR },
    head: [['#', 'Type', 'Width', 'Length', 'Slope', 'Cost']],
    body: result.layout.fields.map((f, i) => [
      `F${i + 1}`,
      f.type,
      `${f.dimensions.width} ft`,
      `${f.dimensions.height} ft`,
      f.slopePct != null ? `${f.slopePct}%` : '—',
      `$${f.cost.toLocaleString()}`,
    ]),
    headStyles: { fillColor: DARK_BG, textColor: BRAND_GREEN, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fillColor: [20, 20, 20], textColor: WHITE, fontSize: 10 },
    alternateRowStyles: { fillColor: PANEL_BG },
    columnStyles: { 5: { halign: 'right' } },
    theme: 'plain',
  });

  curY = (doc as any).lastAutoTable.finalY + 10;

  // ── Support facilities ────────────────────────────────────────────────────
  if (result.layout.facilities.length > 0) {
    if (curY > PH - 60) { doc.addPage(); addFooter(); curY = MT + 8; }

    sectionTitle(doc, 'SUPPORT FACILITIES', ML, curY); curY += 7;

    (doc as any).autoTable({
      startY: curY,
      margin: { left: ML, right: MR },
      head: [['Facility', 'Area', 'Est. Cost']],
      body: result.layout.facilities.map(f => [
        f.name,
        `${f.area.toLocaleString()} sq ft`,
        `$${f.cost.toLocaleString()}`,
      ]),
      headStyles: { fillColor: DARK_BG, textColor: BRAND_GREEN, fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fillColor: [20, 20, 20], textColor: WHITE, fontSize: 10 },
      alternateRowStyles: { fillColor: PANEL_BG },
      columnStyles: { 2: { halign: 'right' } },
      theme: 'plain',
    });

    curY = (doc as any).lastAutoTable.finalY + 10;
  }

  addFooter();

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // PAGE 3 (if needed) — RECOMMENDATIONS + WARNINGS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  if (result.recommendations.length > 0 || result.warnings.length > 0) {
    if (curY > PH - 80) { doc.addPage(); curY = MT + 8; }

    if (result.warnings.length > 0) {
      sectionTitle(doc, '⚠  WARNINGS', ML, curY, [...WARN_YELLOW]); curY += 7;
      result.warnings.forEach(w => {
        doc.setFontSize(9);
        doc.setTextColor(...WARN_YELLOW);
        const lines = doc.splitTextToSize(`• ${w}`, CW - 8);
        doc.text(lines, ML + 4, curY);
        curY += lines.length * 5 + 2;
        if (curY > PH - 30) { doc.addPage(); addFooter(); curY = MT + 8; }
      });
      curY += 4;
    }

    if (result.recommendations.length > 0) {
      sectionTitle(doc, 'RECOMMENDATIONS', ML, curY); curY += 7;
      result.recommendations.forEach(r => {
        doc.setFontSize(9);
        doc.setTextColor(...WHITE);
        const lines = doc.splitTextToSize(`• ${r}`, CW - 8);
        doc.text(lines, ML + 4, curY);
        curY += lines.length * 5 + 2;
        if (curY > PH - 30) { doc.addPage(); addFooter(); curY = MT + 8; }
      });
    }

    addFooter();
  }

  // ── Insurance CTA — last page ─────────────────────────────────────────────
  doc.addPage();
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, PW, PH, 'F');

  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, PH / 2 - 55, PW, 4, 'F');

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND_GREEN);
  doc.text('Ready to protect your investment?', PW / 2, PH / 2 - 38, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...WHITE);
  doc.text(
    `Specialty insurance for ${label.toLowerCase()}s — liability, property, equipment, and more.`,
    PW / 2, PH / 2 - 26, { align: 'center' }
  );

  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text('Visit specialtyinsurancesc.com to get a quote tailored to your facility.', PW / 2, PH / 2 - 14, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(...BRAND_GREEN);
  doc.setFont('helvetica', 'bold');
  doc.text('specialtyinsurancesc.com', PW / 2, PH / 2 + 4, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(
    'This feasibility report is for planning purposes only and does not constitute professional engineering or legal advice.',
    PW / 2, PH - 30, { align: 'center' }
  );
  doc.text('Insurance quotes are subject to underwriting review.', PW / 2, PH - 24, { align: 'center' });

  addFooter();

  // ── Save ──────────────────────────────────────────────────────────────────
  const slug = label.toLowerCase().replace(/\s+/g, '-');
  const dateSlug = new Date().toISOString().split('T')[0];
  doc.save(`land-optimizer-${slug}-${dateSlug}.pdf`);
}

// ── Utility ───────────────────────────────────────────────────────────────────
function sectionTitle(
  doc: any, text: string, x: number, y: number,
  color: number[] = [...BRAND_GREEN]
) {
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...color as [number, number, number]);
  doc.text(text, x, y);
  doc.setDrawColor(...color as [number, number, number]);
  doc.setLineWidth(0.5);
  doc.line(x, y + 1.5, x + 185, y + 1.5);
}
